import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL, isSupabaseConfigured } from '@/lib/supabase/config';
import { CSP_RESPONSE_HEADER, cspFor, makeNonce } from '@/lib/security/csp';

/**
 * Refreshes the Supabase session on every request, and sets the CSP.
 *
 * Server components cannot write cookies, so without this the access token
 * would expire and the user would be silently signed out mid-session — on a
 * screen showing legal deadlines, that is a bad way to find out. The middleware
 * is the one place that can both read the request cookies and write refreshed
 * ones onto the response.
 *
 * It deliberately does NOT gate access to the screens. Signed out, the app
 * still renders the §11 reference dataset behind its "Seeded data" banner,
 * which is what makes it viewable at all today. Access control for real rows is
 * row-level security, keyed to auth.uid() — a redirect here would be a UI
 * convenience, not the boundary.
 */
export async function middleware(request: NextRequest) {
  const nonce = makeNonce();
  const csp = cspFor(nonce);

  /*
   * The nonce reaches Next's own script tags only if it can read the policy off
   * the *request*, so the request headers carry the enforcing name
   * (`Content-Security-Policy`) while the response carries the Report-Only one.
   *
   * That asymmetry looks like a mistake and is the opposite. Next parses
   * `content-security-policy` specifically; hand it the Report-Only name and it
   * finds no nonce, emits unnonced scripts, and the policy we are supposedly
   * trialling would report a violation for every script on every page —
   * drowning the real signal in noise generated by the mechanism itself.
   *
   * `x-nonce` is the copy server components read when they need to nonce
   * something of their own.
   */
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-nonce', nonce);
  requestHeaders.set('Content-Security-Policy', csp);

  const withCsp = (res: NextResponse): NextResponse => {
    res.headers.set(CSP_RESPONSE_HEADER, csp);
    return res;
  };

  let response = NextResponse.next({ request: { headers: requestHeaders } });

  // Before the Supabase early return: the policy is not conditional on the
  // backend being reachable. The e2e suite runs unconfigured, and a header that
  // only appears in production is a header nothing tests.
  if (!isSupabaseConfigured()) return withCsp(response);

  const supabase = createServerClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        for (const { name, value } of cookiesToSet) {
          request.cookies.set(name, value);
        }
        // Rebuilt with the same augmented headers — dropping `requestHeaders`
        // here would strip the nonce from Next's scripts on exactly the
        // requests that refresh a session, which is most of them once signed in.
        response = NextResponse.next({ request: { headers: requestHeaders } });
        for (const { name, value, options } of cookiesToSet) {
          response.cookies.set(name, value, options);
        }
      },
    },
  });

  // Touching getUser() is what triggers the refresh. The result is unused here
  // on purpose — the pages read it themselves.
  await supabase.auth.getUser();

  // Last, not earlier: `setAll` above reassigns `response`, so a header set
  // before that point would be silently discarded.
  return withCsp(response);
}

export const config = {
  matcher: [
    /*
     * Everything except static assets and the icon — refreshing a session on a
     * stylesheet request is pure overhead.
     */
    '/((?!_next/static|_next/image|favicon.ico|icon.svg|manifest.webmanifest).*)',
  ],
};
